# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.50201251 0.41054928 0.51523249]
  [0.58422633 0.20556042 0.76434047]
  [0.22077507 0.94086433 0.97971305]]

 [[0.6795185  0.0075092  0.01478123]
  [0.0249073  0.48569839 0.76916409]
  [0.15733893 0.07234449 0.02454025]]

 [[0.68706269 0.93533698 0.90043849]
  [0.55338271 0.33629202 0.2948393 ]
  [0.34256645 0.65927626 0.22600984]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:

diag = np.eye(5,5)
for i in range(1,5):
    diag[i,i-1] = i
print(diag)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
arr = np.zeros((8,8))
#i=0
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr.astype(int))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
arr = np.random.rand(5,5)
print("Array: ",arr)
normal = np.linalg.norm(arr)
normal_array=arr/normal
print("Normalized Array:",normal_array)


Array:  [[0.3397128  0.1790127  0.64260713 0.17304208 0.42026249]
 [0.50205032 0.927063   0.81601618 0.94834403 0.79529285]
 [0.69212374 0.45379297 0.65214322 0.7554138  0.37337857]
 [0.4139316  0.50149587 0.25378522 0.98593118 0.86368789]
 [0.94405794 0.35589145 0.73001015 0.56726963 0.35502507]]
Normalized Array: [[0.10689125 0.05632667 0.2021975  0.05444801 0.13223635]
 [0.15797104 0.29170206 0.25676097 0.29839817 0.25024034]
 [0.21777799 0.14278678 0.20519805 0.23769232 0.11748425]
 [0.13024433 0.15779659 0.07985398 0.31022504 0.27176096]
 [0.29704954 0.11198189 0.22969902 0.17849242 0.11170928]]


# 5. How to find common values between two arrays?

In [5]:
a1 = np.array([1,2,6,3,4,5,7,9])
a2= np.array([11,6,8,12,3,77,30,9,55,81])
print("Common Values: ",np.intersect1d(a1,a2))

Common Values:  [3 6 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import datetime
today=datetime.date.today()
yesterday=today - datetime.timedelta(days=1)
tomorrow = today+datetime.timedelta(days=1)

print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)

Yesterday:  2021-03-21
Today:  2021-03-22
Tomorrow:  2021-03-23


# 7. Consider two random array A and B, check if they are equal

In [7]:
a3=np.random.rand(3,3)
a4=np.random.rand(3,3)
print("a3:",a3)
print("a4:",a4)
if (a3==a4).all():
    print("They are equal")
else:
    print("They are not equal")

a3: [[0.78253153 0.72526079 0.84183924]
 [0.31849162 0.7593217  0.04248998]
 [0.98007737 0.50799532 0.31981929]]
a4: [[0.34236484 0.88160456 0.28834077]
 [0.02888507 0.01793547 0.17535915]
 [0.95901679 0.79500053 0.90688238]]
They are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0

In [8]:
import numpy as np
a = np.random.random(10)
print("Original array:")
print(a)
a[a.argmax()] = 0
print("Maximum value replaced by 0:")
print(a)

Original array:
[0.39872168 0.16943289 0.45665513 0.20297273 0.83319223 0.75984644
 0.79892388 0.92133234 0.12843831 0.42600369]
Maximum value replaced by 0:
[0.39872168 0.16943289 0.45665513 0.20297273 0.83319223 0.75984644
 0.79892388 0.         0.12843831 0.42600369]


# 9. How to print all the values of an array?

In [9]:
a6 = np.array([[10,12,30],[11,22,33],[22,55,88]])
print(a6)

[[10 12 30]
 [11 22 33]
 [22 55 88]]


# 10.Subtract the mean of each row of a matrix

In [10]:
matrix = np.random.rand(2,2)
print(matrix)
new_matrix = matrix - matrix.mean(axis=1,keepdims=True)
print(new_matrix)

[[0.09102633 0.34212075]
 [0.81413404 0.23348654]]
[[-0.12554721  0.12554721]
 [ 0.29032375 -0.29032375]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [11]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 5. 1. 2. 3. 4. 7. 2. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [12]:
import numpy as np
arr3 = np.random.randint(0,10,(3,3))
arr4= np.random.randint(0,10,(3,3))

print(arr3)
print(arr4)
np.diag(np.dot(arr3, arr4))

[[0 7 8]
 [1 5 4]
 [0 9 6]]
[[2 3 3]
 [8 4 8]
 [3 1 9]]


array([ 80,  27, 126])

# 13.How to find the most frequent value in an array?

In [13]:
import numpy as np
m = np.random.randint(0,10,10)
print (m)
print('Frequent Number:', np.bincount(m).argmax())

[6 4 8 6 9 9 0 6 6 6]
Frequent Number: 6


# 14.How to get the n largest values of an array

In [14]:
import numpy as np
x=np.arange(45)
print(x)
np.random.shuffle(x)
n=1
print(x[np.argsort(x)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
[44]


In [15]:
np.max(x)

44

# 15.How to create a record array from a regular array?

In [16]:
import numpy as np
a =np.array(['Hello','Byee','Hello World'])
b=np.array([10,20,30])
c=np.array(['a','b','c'])
result=np.core.records.fromarrays([a,b,c])

In [17]:
print(result[0])
print(result[1])
print(result[2])

('Hello', 10, 'a')
('Byee', 20, 'b')
('Hello World', 30, 'c')
